# Generated by Django 5.1.3 on 2024-11-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_item_alter_task_due_time_task_items_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='items_needed',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
